---
- hosts: all
  become: yes
  tasks:
    - name: Install depends package
      ansible.builtin.yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: latest
        update_cache: true

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Install Docker-CE
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Add user docker
      user:
        name: dockeruser
        groups: docker
        append: yes
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Execute shell
      ansible.builtin.shell: docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -it --name elk sebp/elk